### ISSUE TITLE
Integrate XT3

### ISSUE THREAD

**Issue by bash-public-willpower** [majuss/lupupy#13]
I am using a XT3 and willing to help integrating it into lupupy.

**Comment by bash-public-willpower** [comment]
For example the smoke detector is not recognized by home assistant

**Comment by majuss** [comment]
So the station itself is working correctly?

**Comment by bash-public-willpower** [comment]
It is working to a certain extent.

**Working**:
Window- / Door contact
Status armed/disarmed

**Not working:**
power switch
smoke detector
status display
motion detector
water sensor
panic button
keypad indoor
indoor siren

**Comment by majuss** [comment]
So everything as expected so far. I always hit a roadblock with the more modern XT stations because nobody is willing to share a VPN access to their network. I would share my screen via discord etc. for the time I'am troubleshooting the integration and you could delete my access every day. You could also limit the VPN to only the XT IP address https://www.reddit.com/r/WireGuard/comments/l5sarn/limit_client_access_to_single_ip_in_lan/

If you're willing to share a VPN acces please contact me via Mail: ich•majuss.de.
An even better solution would be, if we get the founding for a newer XT station so that I can tinker with it locally.

Something like this: https://www.ebay-kleinanzeigen.de/s-anzeige/lupusec-xt3-alarmanlage-smart-komplettpaket-gebraucht-top/2380802780-87-622

**Comment by suaveolent** [comment]
> It is working to a certain extent.
> 
> **Working**: Window- / Door contact Status armed/disarmed
> 
> **Not working:** power switch smoke detector status display motion detector water sensor panic button keypad indoor indoor siren

Smoke and water sensors should work in the upcoming release of Home Assistant.

See https://github.com/home-assistant/core/pull/103905

**Comment by Antonio-di-Houten** [comment]
I have a Lupus Electronics (abbr.: L) XT2-plus (2G sim/mobile version, firmware: HPGW-G 0.0.3G) and Home Assistant (abbr.: HA) on a Minisforum GK50 (X86-64) with HAOS (Core 2023.12.3, Supervisor 2023.11.6, Operating system 11.2, Frontend 20231208.2).  So all the latest firmware on 18-dec.-2023.  I have also an old XT1 (not in use now).
On HA I placed the “Password” of L in the secrets.yaml file and in the configuration.yaml file a variable for the “Password” pointing to the variable with value in secrets.yaml. It works fine (same as “Password” directly in the configuration.yaml file).
I made a Dashboard on for the “L stuff”.

I am NOT familiar with GitHub. I can program but am not familiar with Python nor the (Python) structure for HA for this integration. **I am willing to help with testing or documentation. Let me know if I can help!** 
See below the result of testing on my L XT2-plus. I added some screen print too.

**The following works with the L integration on HA:**
– Alarm on/off for Area 1 (on Android App or WebUI):
….ARM-Absent (not at home).
….Activate (sort of ARM) of HOME-1.
….De-activate/DISARM whatever is ARMED/active, so on HA (as on L) for Area 1 there is NO
….separate DISARM/de-activate for Absent, HOME-1, HOME-2 or Home-3, all will be
….DISARMED/de-activated with 1 button DISARM (as on L). 
….I can activate/ARM HOME-2 or HOME-3 on L and thus DISARM/de-activate it on HA. 
– L Door/Window contacts: 
….Fenster- / Türkontakt (weiß), L part# 12002, RF (end of life). Status goes ON to OFF v.v..
….Fenster- / Türkontakt V2 (weiß), L part# 12113, RF. Status goes ON to OFF v.v..

**Not tested (a little bit difficult) on HA:**
– L Smoke detector: 
….Rauchmelder V2, L part# 12117, RF. Does show up in HA, as:
….friendly_name: L Rookmelder tussenhal bgg
….binary_sensor.l_rookmelder_tussenhal_bgg 

**The following _DOES NOT WORK_ with the L integration on HA (do work on L):**
– Alarm on/off for Area 1 (on Android App or WebUI): 
….Activate (sort of ARM) of HOME-2 or HOME-3.
– Alarm on/off for Area 2 (on Android App or WebUI): 
….Does not show on HA.
….ARM-Absent (not at home).
….Activate (sort of ARM) of HOME-1 or HOME-2 or HOME-3.
….De-activate/DISARM whatever is ARMED/active.

– L smart plug (Power switch): 
….ZigBee Funksteckdose L part# 12133, ZigBee S
….Does show in HA as:  
….friendly_name: L slimme plug mobiel
….Is always “On” in HA , Change in HA to “Off” does not work either.
….Change at L to “On” or “Off” does not change status “On” at HA.
– OSRAM smart plug Zigbee (Power switch):
….Does show in HA as:  
….friendly_name: Os Plug Camera PTZ
….friendly_name: Os Plug Schuur camera
….friendly_name: Os Plugstekker Camera Keuken
….Same issues as : “L slimme plug mobiel” above.
– Lidl SilverCrest Zigbee garden smart plugs (Power switches):
….friendly_name: Li tuin-stopcont 18m in schuur
….Same issues as : “L slimme plug mobiel” above

**I could also test components/devices:**
– Not active on my L: Hitzemelder, L Part#  12018, RF
– Not active on my L: Linienbewegungsmelder, L part# 12110, RF
– Active on my L      : Keypad, L part#. 12001, RF (end of Life). Does not show in HA.
– A lot more components/devices of L or the brand SMaBit. 

**Some screen HA and L:**:
![01 HA LE integration](https://github.com/majuss/lupupy/assets/79230275/362a29e0-47d8-45bd-b56d-921355b15d3d)
![02 HA LE integration](https://github.com/majuss/lupupy/assets/79230275/6b71ed49-ae60-40c4-b2e2-969aa788c81d)
![03 HA L OSRAM SWITCH on ZHA](https://github.com/majuss/lupupy/assets/79230275/63c2d7f8-3cea-4db2-ad52-33fbb5e065a5)
![04 HA L OSRAM SWITCH on L](https://github.com/majuss/lupupy/assets/79230275/951259b9-19c1-4125-b068-d9a6fb1ee7ec)
![05 HA L ARM - Ingeschakeld voor vertrek-afwezig op L scherm](https://github.com/majuss/lupupy/assets/79230275/bea2711b-58e7-4181-9b60-a0b7d726cbe7)

**Comment by suaveolent** [comment]
Thanks for your feedback. However, your description is rather long and hard to read. 
Please only describe what does not work instead of what works and what you could not test.
Also please focus on one bug/issue.

If I understood it correctly, the following does not work.
Can you please create separate issues for at least:

- [Bug] State value of zigbee sensors not correct
- [Bug] Arm/disarm for Area 2 not working
- [Bug] ...

This helps us focus on specific issues rather than having one large issue.

Please also bear in mind to have a consistent description, e.g.  you write:

> The following **DOES NOT WORK** with the L integration on HA (do work on L):
> Alarm on/off for Area 1 (on Android App or WebUI):

 But also:
 > The following **works** with the L integration on HA:
 > – Alarm on/off for Area 1 (on Android App or WebUI):


Please use the following template for each bug report:

```---
name: Bug Report
about: Create a bug report to help us improve

---

## Bug Report

**Describe the bug:**
A clear and concise description of what the bug is.

**To Reproduce:**
Steps to reproduce the behavior:

1. Step 1
2. Step 2
3. ...

**Expected behavior:**
A clear and concise description of what you expected to happen.

**Screenshots:**
If applicable, add screenshots to help explain your problem.

**Environment:**
- OS: [e.g., Windows 10]
- Browser: [e.g., Chrome, Firefox]
- Version: [e.g., 1.0.0]

**Additional context:**
Add any other context about the problem here.

---

```

**Comment by suaveolent** [comment]
I am closing this issue with the release of HA 2023.12 (https://www.home-assistant.io/changelogs/core-2023.12)

**Comment by suaveolent** [comment]
I am closing this issue with the release of HA 2023.12 (https://www.home-assistant.io/changelogs/core-2023.12)
