### ISSUE TITLE
History not working?

### ISSUE THREAD

**Issue by sotima** [majuss/lupupy#2]
Hi, 
first of all thanks for the great work! I am having an issue here: How do I get the history? I am seeing all my power switches, the binary sensors and the panel. But how can I get the history?
I have the XT1 with latest firmware and I am using Homeassistant 0.94.2 with Hass.io.

**Comment by majuss** [comment]
The history is not accessible through homeassistant. What do you want to do with the history? You can get all events inside the hass logbook.

**Comment by sotima** [comment]
Wow! Thanks for the quick response! The plan was to view the history in a list, for example to check the presence of a person.

**Comment by sotima** [comment]
The only entries in the hass logBook I can find, is "Changed to armed_away" or "Changed to disarmed". But not from whom those changes where made.

**Comment by majuss** [comment]
Ah ok, this is somewhat difficult to implement into hass. You could run a cronjob with lupupy which writes into a file and then manipulate it with awk and sed. After that read the file in with a hass file-sensor.

This is somewhat finicky but should work.

**Comment by sotima** [comment]
OK, thank you for your effort! I managed to implement it somehow using node-red and a customized version of the custom-card "list-card". But I thought there could be a more elegant way using your component.

**Comment by majuss** [comment]
Nope there is no way yet sorry :D
Maybe I can implement a history sensor in hass... But I'am not sure. It's getting on my todo :)

**Comment by sotima** [comment]
That would be great! I tried today to get to understand your component. But I have absolutely no experience in python. Another nice add-on (even more important, I think) would be the motion sensor, because most XT1-Sets come with one motion sensor.

**Comment by majuss** [comment]
I will work on the motion sensor, but as far as I know the update-time will be rather slow, because the Lupus WebUI is updating not very often and it's the only connection between hass and the XT.

**Comment by majuss** [comment]
Great news: I got a motion sensor and working now on an implementation. It seems like, it's updating every 0.5 seconds.

EDIT: It will take some more time, since my sensor is acting quite unexpected... Are your motion sensors pushing "Bildereignisse" to the webinterface?

**Comment by majuss** [comment]
So I see no way to capture the triggering of the motion sensor inside the webinterface... Closed until somebody finds a solution.
