### ISSUE TITLE
Could you please file a .tar.gz release?

### ISSUE THREAD

**Issue by onkelbeh** [majuss/lupupy#3]
Hi,

I would like to use your integration in my [Gentoo Overlay for Home Assistant](https://github.com/onkelbeh/HomeAssistantRepository).

Therefor I would need a release file in tar.gz format.
Home Assistant currently requires: `lupupy==0.0.17`

A release on Github would be OK,
but a Pypi tar.gz release **would be preferred**, because this could take use of Gentoo's mirror system.

Most of the other integrations do both.

Thanks
 \B.

**Comment by majuss** [comment]
https://github.com/home-assistant/home-assistant/pull/28989

It's in the making.

**Comment by onkelbeh** [comment]
Thanks :-)

**Comment by onkelbeh** [comment]
0.0.18 is OK.
0.0.17 still on the mirror, will remove in a few months when its not more needed.

**Comment by majuss** [comment]
0.0.20 is also on pypi as tar.gz. Will homeassistant reflect a triggered alarm? I can't check it right now and a user has problems with it: https://github.com/majuss/lupupy/issues/7

**Comment by onkelbeh** [comment]
HA currently uses lupupy-0.0.18, everything (for me) is OK now.
You can find my current version [here](https://github.com/onkelbeh/HomeAssistantRepository/tree/master/dev-python/lupupy).
