### ISSUE TITLE
Modification of  __init__.py required

### ISSUE THREAD

**Issue by Joezi79** [majuss/lupupy#4]
Hello, I am running version 1.0.72 in Lupusec XT1. In this version, there is no login request required. Instead, authentication is done by basic authentication. Your script is only running if I commend out line 30 in file __init__,py (#self._request_post('login')). I do not want to upgrade my XT1. So, I need modified init.py file. I would like to use lupupy in hassio. In Hassio, if i would modify the init.py, it would be overwritten by the next updade. Therefore, I am looking for alternative approach. I tried to add lupupy as custom_component, but I failed. Maybe, you can help me?

**Comment by majuss** [comment]
What is hindering the upgrade of the firmware? I cannot provide different version of lupupy for specific firmwares. I will only support the latest.

Even if the device bricks while upgrade, they will send you a new one. And it's like 30 € on eBay so no big deal.
