### ISSUE TITLE
Integration XT2 Lupusec. 

### ISSUE THREAD

**Issue by g3orgs** [majuss/lupupy#5]
Hello majuss, 

is it possible to adapt the code for the xt2 (Home Assistant)? I could help with tracing since I have the device and some sensors there.

best regards. contact me.

**Comment by majuss** [comment]
https://github.com/majuss/lupupy/pull/1

See this PR. We need manpower to integrate and test it.

**Comment by majuss** [comment]
@g3orgs please try latest release
