### ISSUE TITLE
Conflicting setup requirement with standard library for Python 3.7 / 3.8

### ISSUE THREAD

**Issue by MartinHjelmare** [majuss/lupupy#6]
- This library supports an integration in Home Assistant.
- One or more of the requirements of this library (see below) conflicts with one or more standard library modules for Python 3.7 and/or 3.8.
- To avoid issues it would be good if this library would remove these conflicting requirements from your library setup requirements or use a condition to only install the requirements when using a lower Python version.
- If a `setup.py` file is used it means updating the `install_requires` list and removing or updating the conflicting requirements.
  - See this blog for how to use a condition in `install_requires`: https://hynek.me/articles/conditional-python-dependencies/
- Found conflicts:
  - `pathlib`

Thanks for your support of Home Assistant!

**Comment by majuss** [comment]
I don't really understand the conflict. Pathlib is fully integrated and usable with Python 3.8 I don't see anything conflicting anywhere?!

**Comment by MartinHjelmare** [comment]
Since this library requires Python 3.5 it doesn't need to install pathlib from PyPI. `pathlib` is already available in the standard library of Python 3.5 and higher.

Overwriting standard libraries with PyPI packages may result in problems. Please remove the `pathlib` requirement from `install_requires`.

**Comment by majuss** [comment]
Done in version 0.0.20 of lupupy.

**Comment by MartinHjelmare** [comment]
Thank you!

**Comment by majuss** [comment]
Thank you as always for the easy to follow instructions and idiot proof, patient explanation!
