### ISSUE TITLE
Doesn't report alarm status "triggered"

### ISSUE THREAD

**Issue by tomoqv** [majuss/lupupy#7]
I am integrating Lupus XT1 in [Home Assistant](https://www.home-assistant.io/integrations/lupusec/), which depends on lupupy. It seems that when the alarm is triggered, that status is not passed on to Home Assistant (https://github.com/home-assistant/core/tree/dev/homeassistant/components/lupusec).

Is that not implemented or is just not working correctly with Home Assistant?

**Comment by majuss** [comment]
It worked when I created the project. Maybe not anymore? Are you sure the setup was successful? Could you look at the logs please. Note that the status will be transmitted a few seconds later, because the webinterface has a rather slow refresh period.

**Comment by tomoqv** [comment]
Ok, I thought it would be one of the main features. I will have another look at the status again when the alarm is triggered.

**Comment by majuss** [comment]
No, live transmission of the status is impossible with the XT1 it will be delayed 1-10 seconds.

**Comment by tomoqv** [comment]
I have tried to trigger the alarm a couple of times now. When armed, the alarmpanel looks like this:
![lupus_alarmpanel_armed](https://user-images.githubusercontent.com/13762919/93221546-3112cb80-f76e-11ea-8e31-d89db7af1da8.png)
and Home Assistsant status looks like this:
![lupus_ha_status](https://user-images.githubusercontent.com/13762919/93221603-412aab00-f76e-11ea-8bd3-2a44fe562e07.png)
After alarm triggers, alarmpanel looks like this:
![lupus_alarmpanel_einbruch](https://user-images.githubusercontent.com/13762919/93221664-51428a80-f76e-11ea-825b-396acbb7927a.png)
but hass still shows the same (even after 30-60 seconds):
![lupus_ha_status](https://user-images.githubusercontent.com/13762919/93221724-63bcc400-f76e-11ea-8b9f-e997beb11a91.png)

**Comment by tomoqv** [comment]
I have also been thinking about what the different attributes really mean:
```
code_format: null
changed_by: null
code_arm_required: true
friendly_name: Lupusec Alarm
icon: 'mdi:security'
supported_features: 3

```
`code_arm_required: true` doesn't actually require me to enter a code to arm, I can arm or disarm it without the code.
`supported_features: 3` which supported features might that be?

Do these features have to do with the alarm_control_panel implementation in hass?

**Comment by majuss** [comment]
Sorry but I don't have time right now to debug all of this. Maybe in the future. The python code is very basic in easily understandable. If you're interested you should give it a go. 
The "Tillstand" will be set by these lines of code
```
elif self._device.is_alarm_triggered:
            state = STATE_ALARM_TRIGGERED
```
Please setup an automation which will notify you, when the alarm was triggered. The exact string will be: "triggered" see here: https://github.com/home-assistant/core/blob/dev/homeassistant/const.py

So I got my XT1 up running again and checked everything. Setting the state seem to work just fine. I don't have any sensors so I can't really debug the triggered alarm at the moment. Just start hass with maximum verbosity: `hass -vvv` and look at the logs.

**Comment by tomoqv** [comment]
> Please setup an automation which will notify you, when the alarm was triggered. The exact string will be: "triggered" see here: https://github.com/home-assistant/core/blob/dev/homeassistant/const.py

I already have an automation that is supposed to trigger on the change from "armed_away" to "triggered", but as the reported state remains at "armed_away", the automation is never triggered.
![lupus-automation-trigger](https://user-images.githubusercontent.com/13762919/93310560-3e2ec980-f805-11ea-90ff-e52ff7d024f4.png)

**Comment by majuss** [comment]
Try to use `lupupy` on it's own and see if the program returns the triggered state.

**Comment by tomoqv** [comment]
> Try to use `lupupy` on it's own and see if the program returns the triggered state.

I am totally willing to do that, but I am struggling to learn how to implement even the simplest python script in hass. I would appreciate if you could point me in the direction of some documentation that could help me.

Thanks

**Comment by majuss** [comment]
On a linux machine run the following commands:
```shell
python3 -m venv lupupy_venv  # Will create a virtual environment which is called lupupy_venv
source lupupy_venv/bin/activate  # Activates the venv
pip3 install lupupy  # Installs lupupy inside the venv
lupupy -u admin -p password -i ip_address --history  # Runs lupupy in command line mode
```

**Comment by tomoqv** [comment]
Ok, thanks. I will try that.

**Comment by tomoqv** [comment]
Sorry to bother you all the time, but this is what I get:
```
(lupupy_venv) tomas@tomas-XPS13:~$ lupupy -u "my_username" -p "my_password" -i "my_ip_address" --history
2020-09-16 12:08:01 INFO (MainThread) [lupupy] Updating all devices...
2020-09-16 12:08:01 INFO (MainThread) [lupupy] Device is not known
2020-09-16 12:08:01 INFO (MainThread) [lupupy] Device is unknown
2020-09-16 12:08:01 INFO (MainThread) [lupupy] Device is not known
2020-09-16 12:08:01 INFO (MainThread) [lupupy] Device is unknown
<html>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1" />
<link rel="stylesheet" type="text/css" href="/css/main.css" />
<head>
<title>Document Error: Unauthorized</title></head>
<body>
<h2>Access Error: Unauthorized</h2>
<p>Access to this document requires a User ID</p>
<a href="/index.htm" target="_top">Go to home</a>
</body>
</html>


2020-09-16 12:08:01 INFO (MainThread) [lupuseccl] --Finished running--
Traceback (most recent call last):
  File "/home/tomas/lupupy_venv/bin/lupupy", line 11, in <module>
    sys.exit(main())
  File "/home/tomas/lupupy_venv/lib/python3.5/site-packages/lupupy/__main__.py", line 164, in main
    call()
  File "/home/tomas/lupupy_venv/lib/python3.5/site-packages/lupupy/__main__.py", line 127, in call
    password=args.password)
  File "/home/tomas/lupupy_venv/lib/python3.5/site-packages/lupupy/__init__.py", line 47, in __init__
    self.get_devices()
  File "/home/tomas/lupupy_venv/lib/python3.5/site-packages/lupupy/__init__.py", line 171, in get_devices
    panelJson = self.get_panel()
  File "/home/tomas/lupupy_venv/lib/python3.5/site-packages/lupupy/__init__.py", line 115, in get_panel
    raise Exception('Unable to get panel')
Exception: Unable to get panel

```

**Comment by tomoqv** [comment]
Running the above command without the quotes I get:
```
2020-09-16 12:15:27 INFO (MainThread) [lupupy] Updating all devices...
2020-09-16 12:15:27 INFO (MainThread) [lupupy] Device is not known
2020-09-16 12:15:27 INFO (MainThread) [lupupy] Device is unknown
2020-09-16 12:15:27 INFO (MainThread) [lupupy] Device is not known
2020-09-16 12:15:27 INFO (MainThread) [lupupy] Device is unknown
2020-09-16 12:15:28 INFO (MainThread) [lupuseccl] --Finished running--
Traceback (most recent call last):
  File "/home/tomas/lupupy_venv/bin/lupupy", line 11, in <module>
    sys.exit(main())
  File "/home/tomas/lupupy_venv/lib/python3.5/site-packages/lupupy/__main__.py", line 164, in main
    call()
  File "/home/tomas/lupupy_venv/lib/python3.5/site-packages/lupupy/__main__.py", line 148, in call
    _LOGGER.info(json.dumps(lupusec.get_history()['hisrows'], indent=4, sort_keys=True))
TypeError: list indices must be integers or slices, not str

```

**Comment by tomoqv** [comment]
Ok, it seems the --history command throws the error. Using --status or --devices I don't get errors.

**Comment by tomoqv** [comment]
This is the output when the alarm is triggered:
```
2020-09-16 12:31:31 INFO (MainThread) [lupupy] Updating all devices...
2020-09-16 12:31:31 INFO (MainThread) [lupupy] Device is not known
2020-09-16 12:31:31 INFO (MainThread) [lupupy] Device is unknown
2020-09-16 12:31:31 INFO (MainThread) [lupupy] Device is not known
2020-09-16 12:31:31 INFO (MainThread) [lupupy] Device is unknown
2020-09-16 12:31:31 INFO (MainThread) [lupuseccl] Mode of panel: Arm
2020-09-16 12:31:31 INFO (MainThread) [lupuseccl] --Finished running--
```
So I guess lupupy simply doesn't report the status "triggered".

**Comment by majuss** [comment]
What does this give you: 
`cat .lupusec_history_cache`

**Comment by tomoqv** [comment]
```
(lupupy_venv) tomas@tomas-XPS13:~$ cat .lupusec_history_cache
�]q(}q(XaqX!Stromversorgung wiederhergestelltqXdqX01/01qXtqX00:00qXsXPanelq	u}q
(hXDisarmq
            hX01/01q
XPanelqu}q(hXArmqhX09/14qhX18:26qXEntré, Keypad, Tomasqu}q(hXEingangqhX09/14qhX18:26qXEntrédörr, Türkontaktqu}q(hXDisarmqhX09/14qhX18:26qXEntré, Keypad, Tomasqu}q(hXArmqhX09/14q hX18:27q!XEntré, Keypad, Tomasq"u}q#(hXEingangq$hX09/14q%hX21:13q&XEntrédörr, Türkontaktq'u}q((hXDisarmq)hX09/14q*hX21:13q+XEntré, Keypad, Cillaq,u}q-(hXArmq.hX09/15q/hX15:58q0X	Webserverq1u}q2(hEinbruchq3hX09/15q4hX15:59q5XÖvervåning, Bewegungsmelderq6u}q7(hXDisarmq8hX09/15q9hX16:01q:X	Webserverq;u}q<(hXArmq=hX09/15q>hX16:03q?X	Webserverq@u}qA(hEinbruchqBhX09/15qChX16:05qDXÖvervåning, BewegungsmelderqEu}qF(hEinbruchqGhX09/15qHhX16:07qIXÖvervåning, BewegungsmelderqJu}qK(hXDisarmqLhX09/15qMhX16:08qNX	WebserverqOu}qP(hXArmqQhX09/15qRhX19:47qSXEntré, Keypad, TomasqTu}qU(hXEingangqVhX09/15qWhX22:23qXXEntrédörr, TürkontaktqYu}qZ(hXDisarmq[hX09/15q\hX22:24q]XEntré, Keypad, Tomasq^u}q_(hX
        Home, Forcedq`hX09/16qahX12:26qbX	Webserverqcu}qd(hXDisarmqehX09/16qfhX12:26qgX	Webserverqhu}qi(hXArmqjhX09/16qkhX12:30qlX	Webserverqmu}qn(hEinbruchqohX12:31qphX09/16qqXÖvervåning, Bewegungsmelderqrue.

```

**Comment by tomoqv** [comment]
After changing line 148 to
`    _LOGGER.info(json.dumps(lupusec.get_history()[10], indent=4, sort_keys=True))`
the --history command gives me
```
2020-09-16 13:06:27 INFO (MainThread) [lupupy] Updating all devices...
2020-09-16 13:06:27 INFO (MainThread) [lupupy] Device is not known
2020-09-16 13:06:27 INFO (MainThread) [lupupy] Device is unknown
2020-09-16 13:06:27 INFO (MainThread) [lupupy] Device is not known
2020-09-16 13:06:27 INFO (MainThread) [lupupy] Device is unknown
2020-09-16 13:06:27 INFO (MainThread) [lupuseccl] {
    "a": "Arm",
    "d": "09/16",
    "s": "Webserver",
    "t": "12:30"
}
2020-09-16 13:06:27 INFO (MainThread) [lupuseccl] --Finished running--
```
There is no difference if I increase the row number from 10 to 20, and at 50 I get "overflow".

**Comment by majuss** [comment]
Ahh the history is pickled. You would need to write a small python program to read the file and unpickle it. Not sure whats happening to the history. As I said I have no functional Lupusec at home.

**Comment by tomoqv** [comment]
With my very basic understanding of python, it seems that it is possible to read the history of lupusec. The length of the history varies, the first record being the oldest and the last record being the newest. As I want to get the newest record, I need to know how many records lupusec.get_history() has.

I guess that, by this, it should also be possible to add e.g. the last_changed and changed_by properties to the alarm_panel entity in hass, which would make it much more useful.

So, from a record like this (I have no idea which character set is used for the history information):
```
   {
        "a": "Einbruch",
        "d": "09/16",
        "s": "\u00d6verv\u00e5ning, Bewegungsmelder",
        "t": "12:31"
    },
```
I would like to extract the event "Einbruch" and when that happens set status to "Triggered". Another way would be to extract the latest history record and extract the event, e.g. "Einbruch" or "Eingang" as well as the sensor/person triggering that event and the date and time when it occured.

It seems to me we have all the needed information available to us. Question is how to best implement it in lupupy? Should "Triggered", i.e. "Einbruch" be treated as an event or a status?

**Comment by majuss** [comment]
I'am really confused by now... The "Triggered" event should be working in lupupy and hass. If not that's a bug and I will fix that.

Your history stuff is a whole other story which I will maybe look at, but AFTER I fixed the bug that hass is not tracking the triggered event. The history of "triggered" etc. is inside your logbook in hass. If not thats a bug.

So please seperate these two things otherwise my brain explodes :D

**Comment by majuss** [comment]
I fixed the --history bug in version 0.0.21 please update in your venv with `pip3 install lupupy --upgrade`.

**Comment by tomoqv** [comment]
> Your history stuff is a whole other story which I will maybe look at, but AFTER I fixed the bug that hass is not tracking the triggered event. The history of "triggered" etc. is inside your logbook in hass. If not thats a bug.

Ok, now it seems to actually report status as "Triggered" to hass:
![lupus_ha_status](https://user-images.githubusercontent.com/13762919/93358456-c8951e80-f841-11ea-99f7-06b8f2763ac7.png)
However, as you can see, status = "triggered" only lasts for 2 seconds before it goes back to status = "armed_away".

**Comment by tomoqv** [comment]
> I fixed the --history bug in version 0.0.21 please update in your venv with `pip3 install lupupy --upgrade`.

Yes, --history now shows full history as output.

**Comment by majuss** [comment]
Yeah so it works as expected... What do you want to change I don't get it sorry. And what did you change on your end, that it's now reporting it in hass? Hass is still using lupupy version 0.0.17...

**Comment by tomoqv** [comment]
Sorry, I must admit I didn't look in the log book before because I never detected the change in status to "triggered" from Lupusec. My automation didn't detect it either, which it now suddenly did. It seems though, that the status "triggered" only exits for a very brief moment.

What I would like, is the ability to parse the json.dumps data in order to extract the history events, such as changed_by, last_changed and entity changed. I guess this should be a separate issue from this one.

Thanks for helping out, I really appreciate it!

**Comment by majuss** [comment]
But it's there inside the logbook. You could always bring that up in a lovelace card or something. Yes the status triggered is only there for 2 seconds. It's really hard to change that, but it is in my opinion also completely irrelevant, because you have your automations that notify you etc. nobody is looking onto their hass dashboard if the alarm was triggered :) when it was triggered is inside the logbook.
