### ISSUE TITLE
Feature requests - motion sensor and arm/disarm history

### ISSUE THREAD

**Issue by tomoqv** [majuss/lupupy#8]
First of all, a big thank you for the work with this. I am successfully integrating my Lupus Alarm with Home Assistant.

However, there are some bits and pieces missing and I though I could maybe be of assistance in some way.

Firstly, there seems to be no way to see the history of who armed or disarmed the alarm, which is displayed looking at the alarm panel in a web browser.

Secondly, motion sensors are not available. I only have one, but it would be nice to see if there has been any motion in the house.

I'll be glad to help out with testing (within Home Assistant) if there is anything I can do.

Thank you!

**Comment by majuss** [comment]
The status of the motion sensor is not transmitted into the webinterface of the Lupus, so it's impossible to read these states. The history of arming could be possible, you have to find a similiar example integrated in hass.

**Comment by tomoqv** [comment]
Yes, you are right, it is not shown in the alarm panel. I have another hass instance, which integrates [Sector Alarm](https://github.com/mgejke/hass-sectoralarm). It shows me the "changed_by" attribute. My Lovelace code for that looks like this:
```
  - type: custom:button-card
    entity: alarm_control_panel.sector_alarm_02602218
    show_label: false
    show_name: true
    show_icon: true
    show_last_changed: true
    name: >
      [[[
      return "Ändrad av " + entity.attributes.changed_by
      ]]]

```

**Comment by majuss** [comment]
You can always just run a file sensor (https://www.home-assistant.io/integrations/file/) on the hidden history file which is inside your home and revealed by:
```
ls -la
```

**Comment by majuss** [comment]
So question is, do you still need the history even when you have the logbook?
https://github.com/royto/logbook-card
This card is basically what you are looking for.

**Comment by tomoqv** [comment]
Yes, I really would like to read the history of the Lupus Alarm too. If we consider the following json history data retrieved from lupupy, some of it but not all will show in the log book.
```
    {
        "a": "Disarm",
        "d": "09/16",
        "s": "Webserver",
        "t": "17:48"
    },
    {
        "a": "Arm",
        "d": "09/16",
        "s": "Front door, Keypad, Cilla",
        "t": "18:12"
    },
    {
        "a": "Eingang",
        "d": "09/16",
        "s": "Front door, Türkontakt",
        "t": "21:32"
    },
    {
        "a": "Disarm",
        "d": "09/16",
        "s": "Front door, Keypad, Tomas",
        "t": "21:33"
    }

```
The log book will show e.g. the following:
![hass_logbook_lupus1](https://user-images.githubusercontent.com/13762919/93449677-50783880-f8d5-11ea-9d27-4f826ba0a63b.png)
![hass_logbook_lupus2](https://user-images.githubusercontent.com/13762919/93449691-5241fc00-f8d5-11ea-8ca1-eda9046bbf1e.png)
But it will not show who armed or disarmed the alarm with the keypad, which the Lupus history tells me.

For that purpose, it would be nice to at least have the attribute "changed_by", and if adding that I guess it wouldn't be too difficult to implement the attribute "last_changed", which could be easily be read and displayed in hass.

**Comment by tomoqv** [comment]
> So question is, do you still need the history even when you have the logbook?
> https://github.com/royto/logbook-card
> This card is basically what you are looking for.

I will look into this card also, but it won't cater for all of my needs as some data is only available in the Lupus history.

**Comment by majuss** [comment]
https://www.home-assistant.io/blog/2020/11/18/release-118/

The logbook card is now a part of the official hass release.

**Comment by tomoqv** [comment]
Ok, I don't have the possibility to test this right now, but are you sure all the history will be visible in the logbook card or only the data that was available in the previous logbook card?

**Comment by majuss** [comment]
As stated, it would be an absolute Nightmare to import the messages from the lupusec webserver to homeassistant. I would just point all users to use hass and not the lupusec app.
